import { Account, Category, Group, Member, Transaction } from './types';

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'mem_husband',
    name: 'Husband',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'admin',
    color: '#2563eb', // Blue
    initials: 'H',
  },
  {
    id: 'mem_wife',
    name: 'Wife',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'member',
    color: '#db2777', // Pink/Rose
    initials: 'W',
  },
];

export const INITIAL_GROUPS: Group[] = [
  {
    id: 'grp_family',
    name: 'Family',
    description: 'Shared household expenses & personal finances',
    currency: 'INR',
    members: INITIAL_MEMBERS,
    inviteCode: 'PAIR-7729-COUPLE',
    createdAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'grp_goa',
    name: 'Goa Trip 2026',
    description: 'Vacation travel, stays & dining',
    currency: 'INR',
    members: INITIAL_MEMBERS,
    inviteCode: 'PAIR-4412-GOATRIP',
    createdAt: '2026-08-10T00:00:00.000Z',
  },
];

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'cat_groceries', name: 'Groceries', iconName: 'ShoppingBag', color: '#10b981', isDefault: true, isActive: true },
  { id: 'cat_fuel', name: 'Fuel & Commute', iconName: 'Fuel', color: '#f59e0b', isDefault: true, isActive: true },
  { id: 'cat_dining', name: 'Dining & Cafes', iconName: 'Utensils', color: '#ef4444', isDefault: true, isActive: true },
  { id: 'cat_shopping', name: 'Shopping', iconName: 'Shirt', color: '#8b5cf6', isDefault: true, isActive: true },
  { id: 'cat_rent', name: 'Rent', iconName: 'Home', color: '#3b82f6', isDefault: true, isActive: true },
  { id: 'cat_utilities', name: 'Utilities & Bills', iconName: 'Zap', color: '#06b6d4', isDefault: true, isActive: true },
  { id: 'cat_travel', name: 'Travel & Trips', iconName: 'Plane', color: '#ec4899', isDefault: true, isActive: true },
  { id: 'cat_entertainment', name: 'Entertainment', iconName: 'Film', color: '#6366f1', isDefault: true, isActive: true },
  { id: 'cat_medical', name: 'Medical & Health', iconName: 'HeartPulse', color: '#14b8a6', isDefault: true, isActive: true },
  { id: 'cat_pet', name: 'Pet Expenses', iconName: 'PawPrint', color: '#f97316', isDefault: false, isActive: true },
  { id: 'cat_other', name: 'Other', iconName: 'Tag', color: '#6b7280', isDefault: true, isActive: true },
];

export const INITIAL_ACCOUNTS: Account[] = [
  // Husband's Accounts
  {
    id: 'acc_husband_hdfc_cc',
    groupId: 'grp_family',
    name: 'HDFC Millennia Credit Card',
    type: 'CREDIT_CARD',
    ownerMemberId: 'mem_husband',
    currency: 'INR',
    isActive: true,
    bankName: 'HDFC Bank',
    lastFourDigits: '8912',
  },
  {
    id: 'acc_husband_sbi_savings',
    groupId: 'grp_family',
    name: 'SBI Savings Account',
    type: 'BANK_ACCOUNT',
    ownerMemberId: 'mem_husband',
    currency: 'INR',
    isActive: true,
    bankName: 'State Bank of India',
    lastFourDigits: '4102',
  },
  {
    id: 'acc_husband_upi',
    groupId: 'grp_family',
    name: 'GPay / UPI (husband@okhdfc)',
    type: 'UPI',
    ownerMemberId: 'mem_husband',
    currency: 'INR',
    isActive: true,
  },
  {
    id: 'acc_husband_cash',
    groupId: 'grp_family',
    name: 'Wallet Cash',
    type: 'CASH',
    ownerMemberId: 'mem_husband',
    currency: 'INR',
    isActive: true,
  },

  // Wife's Accounts
  {
    id: 'acc_wife_icici',
    groupId: 'grp_family',
    name: 'ICICI Salary Account',
    type: 'BANK_ACCOUNT',
    ownerMemberId: 'mem_wife',
    currency: 'INR',
    isActive: true,
    bankName: 'ICICI Bank',
    lastFourDigits: '9034',
  },
  {
    id: 'acc_wife_hdfc_cc',
    groupId: 'grp_family',
    name: 'HDFC Regalia Credit Card',
    type: 'CREDIT_CARD',
    ownerMemberId: 'mem_wife',
    currency: 'INR',
    isActive: true,
    bankName: 'HDFC Bank',
    lastFourDigits: '3321',
  },
  {
    id: 'acc_wife_upi',
    groupId: 'grp_family',
    name: 'PhonePe UPI',
    type: 'UPI',
    ownerMemberId: 'mem_wife',
    currency: 'INR',
    isActive: true,
  },
  {
    id: 'acc_wife_cash',
    groupId: 'grp_family',
    name: 'Hand Cash',
    type: 'CASH',
    ownerMemberId: 'mem_wife',
    currency: 'INR',
    isActive: true,
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_01',
    groupId: 'grp_family',
    type: 'EXPENSE',
    amount: 1000,
    currency: 'INR',
    date: '2026-08-15',
    createdAt: '2026-08-15T08:30:00.000Z',
    createdByMemberId: 'mem_husband',
    description: 'Weekly Organic Groceries & Vegetables',
    categoryId: 'cat_groceries',
    paidByMemberId: 'mem_husband',
    accountId: 'acc_husband_hdfc_cc',
    splitMethod: 'EQUAL',
    splits: [
      { memberId: 'mem_husband', amount: 500, percentage: 50 },
      { memberId: 'mem_wife', amount: 500, percentage: 50 },
    ],
    notes: 'Nature Basket order for the week',
  },
  {
    id: 'tx_02',
    groupId: 'grp_family',
    type: 'EXPENSE',
    amount: 2000,
    currency: 'INR',
    date: '2026-08-14',
    createdAt: '2026-08-14T14:15:00.000Z',
    createdByMemberId: 'mem_wife',
    description: 'Car Petrol Refill - Shell Station',
    categoryId: 'cat_fuel',
    paidByMemberId: 'mem_wife',
    accountId: 'acc_wife_icici',
    splitMethod: 'EQUAL',
    splits: [
      { memberId: 'mem_husband', amount: 1000, percentage: 50 },
      { memberId: 'mem_wife', amount: 1000, percentage: 50 },
    ],
    notes: 'Full tank for weekend trip',
  },
  {
    id: 'tx_03',
    groupId: 'grp_family',
    type: 'EXPENSE',
    amount: 3200,
    currency: 'INR',
    date: '2026-08-12',
    createdAt: '2026-08-12T20:45:00.000Z',
    createdByMemberId: 'mem_husband',
    description: 'Dinner at Olive Bistro & Bar',
    categoryId: 'cat_dining',
    paidByMemberId: 'mem_husband',
    accountId: 'acc_husband_hdfc_cc',
    splitMethod: 'PERCENTAGE',
    splits: [
      { memberId: 'mem_husband', amount: 1920, percentage: 60 },
      { memberId: 'mem_wife', amount: 1280, percentage: 40 },
    ],
    notes: 'Husband ordered wine (60/40 custom split)',
  },
  {
    id: 'tx_04',
    groupId: 'grp_family',
    type: 'EXPENSE',
    amount: 4800,
    currency: 'INR',
    date: '2026-08-10',
    createdAt: '2026-08-10T11:00:00.000Z',
    createdByMemberId: 'mem_husband',
    description: 'Electricity & High-speed Wifi Bill',
    categoryId: 'cat_utilities',
    paidByMemberId: 'mem_husband',
    accountId: 'acc_husband_sbi_savings',
    splitMethod: 'EQUAL',
    splits: [
      { memberId: 'mem_husband', amount: 2400, percentage: 50 },
      { memberId: 'mem_wife', amount: 2400, percentage: 50 },
    ],
  },
  {
    id: 'tx_05',
    groupId: 'grp_family',
    type: 'DIRECT_TRANSFER',
    amount: 10000,
    currency: 'INR',
    date: '2026-08-08',
    createdAt: '2026-08-08T10:00:00.000Z',
    createdByMemberId: 'mem_husband',
    description: 'Personal short-term loan for course fee',
    fromMemberId: 'mem_husband',
    toMemberId: 'mem_wife',
    accountId: 'acc_husband_sbi_savings',
    notes: 'Direct bank transfer from Husband to Wife',
  },
  {
    id: 'tx_06',
    groupId: 'grp_family',
    type: 'SETTLEMENT',
    amount: 6000,
    currency: 'INR',
    date: '2026-08-09',
    createdAt: '2026-08-09T18:30:00.000Z',
    createdByMemberId: 'mem_wife',
    fromMemberId: 'mem_wife',
    toMemberId: 'mem_husband',
    accountId: 'acc_wife_upi',
    notes: 'Partial loan payback via UPI',
  },
  {
    id: 'tx_07',
    groupId: 'grp_family',
    type: 'EXPENSE',
    amount: 1500,
    currency: 'INR',
    date: '2026-08-05',
    createdAt: '2026-08-05T16:20:00.000Z',
    createdByMemberId: 'mem_wife',
    description: 'Golden Retriever Veterinary Checkup & Meds',
    categoryId: 'cat_pet',
    paidByMemberId: 'mem_wife',
    accountId: 'acc_wife_hdfc_cc',
    splitMethod: 'AMOUNT',
    splits: [
      { memberId: 'mem_husband', amount: 1000 },
      { memberId: 'mem_wife', amount: 500 },
    ],
    notes: 'Annual vaccination',
  },
];
